<?php /** @var Mastercard_Mpgs_Block_Checkout_Button_Amex $this */ ?>

<button id="amex_session_create" type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout">
    <span><?php echo $this->__('Place Order') ?></span>
</button>

<script type="text/javascript">
    var AmexCheckout = Class.create();
    AmexCheckout.prototype = {
        config: {},

        initialize: function (elem, url) {
            this.config.url = url;
            $(elem).observe('click', this.createSession.bind(this));
        },

        createSession: function () {
            new Ajax.Request(this.config.url, {
                onSuccess: this.didCreateSession.bind(this),
                onFailure: this.didFail.bind(this)
            })
        },

        didCreateSession: function () {
            console.log('session created', arguments);
        },

        didFail: function (transport) {
            if (transport.responseJSON.exception) {
                console.error('Backend exception: %s', transport.responseJSON.exception);
            }
            alert('<?php echo $this->__("Unable to load Amex Express Checkout, please try again later.") ?>');
        }
    };
    new AmexCheckout('amex_session_create', '<?php echo Mage::getUrl('mastercard/session/wallet') ?>');
</script>
