<?php /** @var Mastercard_Mpgs_Block_Checkout_Button_Amex $this */ ?>
<div id="amex-express-checkout"></div>
<script type="text/javascript">
    var AmexCheckout = Class.create();
    AmexCheckout.prototype = {
        config: {},

        initialize: function (config) {
            this.config = config;
            if (window.payment.currentMethod === 'Mastercard_amex') {
                this.loadAdapter();

                new MutationObserver(this.adapterLoaded)
                    .observe($('amex-express-checkout'), { childList: true });
            }
        },

        loadAdapter: function (event) {
            window.aecCallbackHandler = this.aecCallbackHandler.bind(this);

            new Ajax.Request(this.config.session_url, {
                onSuccess: this.didCreateSession.bind(this),
                onFailure: this.didFail.bind(this),
                onLoading: function () {
                    $('mpgs-loading').show();
                }
            })
        },

        didCreateSession: function (response) {
            var config = response.responseJSON;

            // Cleanup any previous tags
            $A(document.getElementsByTagName('amex:init')).each(function (item) {
                item.remove();
            });

            var amex = new Element('amex:init', {
                client_id: this.config.client_id,
                theme: 'responsive',
                env: this.config.env,
                callback: 'aecCallbackHandler'
            });

            var amexBuy = new Element('amex:buy', {
                encrypted_data: config.wallet.amexExpressCheckout.encryptedData
            });

            amex.insert(amexBuy);
            document.body.insert(amex);

            var loader = new Element('script', {
                type: 'text/javascript',
                src: this.config.component_url
            });
            document.body.insert(loader);
        },

        didFail: function (transport) {
            if (transport.responseJSON.exception) {
                console.error('Backend exception: %s', transport.responseJSON.exception);
            }
            alert('<?php echo $this->__("Error in Amex Express Checkout, please try again later.") ?>');
        },

        aecCallbackHandler: function (response) {
            new Ajax.Request(this.config.place_order_url, {
                method: 'post',
                parameters: $H(response),
                onSuccess: this.didCompleteOrder.bind(this),
                onFailure: this.didFail.bind(this),
                onLoading: function () {
                    $('amex-express-checkout').hide();
                    $('mpgs-please-wait').show();
                }
            });
        },

        adapterLoaded: function () {
            $('mpgs-loading').hide();
        },

        didCompleteOrder: function (response) {
            if (!response.responseJSON.success_url) {
                console.error('Backend exception: Return Data does not contain success URL');
                alert('<?php echo $this->__('Something went wrong, please try again later.') ?>');
            }
            location.href = response.responseJSON.success_url;
        }
    };
    new AmexCheckout(<?php echo $this->getJsConfig() ?>);
</script>
