<?php
/**
 * Copyright (c) 2016-2019 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<?php /** @var Mastercard_Mpgs_Block_Checkout_Button_Form $this */ ?>
<button type="submit"
        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Place Order')) ?>"
        onclick="mastercardForm.saveOrder();"
        class="button btn-checkout"
        id="mastercard_hostedform_placeorder">
    <span><?php echo $this->__('Place Order') ?></span>
</button>
