<?php /** @var Mastercard_Mpgs_Block_Checkout_Button_AbstractButton $this */ ?>
<?php $action = sprintf("showMpgsLightbox('%s');", $this->getQuote()->getId()); ?>

<button type="submit"
        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Place Order')) ?>"
        class="button btn-checkout" onclick="<?php echo $action; ?>">
    <span><?php echo $this->__('Place Order') ?></span>
</button>
