<?php
/**
 * Copyright (c) 2016-2019 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<div class="buttons-set wallet-checkout">
    <?php echo $this->getChildHtml('agreements') ?>
    <p class="f-left">
        <?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a>
    </p>
    <div id="agreements-protector">
        <?php echo $this->getChildHtml('button') ?>
    </div>
    <span class="please-wait" id="mpgs-loading" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading...')) ?>" class="v-middle" /> <?php echo $this->__('Loading...') ?>
    </span>
    <span class="please-wait" id="mpgs-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
    </span>
</div>
<script type="text/javascript">
    $('checkout-review-submit').hide();
    $('agreements-protector').addEventListener('click', function (e) {
        var agreementsFilled = true;
        $A(document.querySelectorAll('.wallet-checkout #checkout-agreements input')).each(function (item) {
            if (agreementsFilled && !item.checked) {
                agreementsFilled = false;
            }
        });
        if (agreementsFilled) {
            return;
        }

        if (e.target.id === 'mastercard_hostedcheckout_placeorder' || e.target.parentElement.id === 'mastercard_hostedcheckout_placeorder') {
            e.stopImmediatePropagation();
            e.stopPropagation();
            alert("<?php echo $this->__('Please agree to all the terms and conditions before placing the order.') ?>");
        }
    }, true);
</script>
