<?php
    /** @var Mastercard_Mpgs_Block_Review $this */
?>
<div class="page-title">
    <h1><?php echo $this->__('Review Your Order') ?></h1>
</div>

<div class="info-set col2-set">
    <h3 class="legend"><?php echo $this->__('Shipping Information') ?></h3>
    <div class="col-1">
        <div class="box">
            <div class="box-content">
                <address><?php echo $this->renderAddress($this->getShippingAddress())?></address>
                <a href="#"><?php echo $this->__('edit') ?></a>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Shipping Method') ?></h3>
            </div>
            <div class="box-content">
                <form method="post" id="shipping_method_form" action="">
                    <?php if ($groups = $this->getShippingRateGroups()):?>
                        <?php $currentRate = $this->getCurrentShippingRate(); ?>
                        <fieldset>
                            <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
                                <?php if (!$currentRate):?>
                                    <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
                                <?php endif;?>
                                <?php foreach ($groups as $code => $rates):?>
                                    <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                                        <?php foreach ($rates as $rate):?>
                                            <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                                                <?php echo $this->renderShippingRateOption($rate)?>
                                            </option>
                                        <?php endforeach;?>
                                    </optgroup>
                                <?php endforeach;?>
                            </select>
                        </fieldset>
                        <p class="actions">
                            <button id="update_shipping_method_submit" type="submit" class="button"><span><span><?php echo $this->__('Update Shipping Method') ?></span></span></button>
                        </p>
                    <?php else: ?>
                        <p><strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong></p>
                    <?php endif;?>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="info-set col2-set">
    <h3 class="legend"><?php echo $this->__('Billing Information') ?></h3>
    <div class="col-1">
        <div class="box">
            <div class="box-content">
                <address><?php echo $this->renderAddress($this->getBillingAddress())?></address>
            </div>
        </div>
    </div>
</div>

<div class="info-set">
    <h3 class="legend"><?php echo $this->__('Items in Your Shopping Cart') ?></h3>
    <div id="details-reload">
        <?php echo $this->getChildHtml('details') ?>
    </div>
</div>

<a href="<?php echo Mage::getUrl('mastercard/review/placeOrder')?>">Place Order</a>
