<?php
/**
 * Copyright (c) 2016-2019 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

    /** @var Mastercard_Mpgs_Block_Review $this */
?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

<div class="page-title">
    <h1><?php echo $this->__('Review Your Order') ?></h1>
</div>

<div class="info-set col2-set">
    <h3 class="legend"><?php echo $this->__('Shipping Information') ?></h3>
    <div class="col-1">
        <div class="box shipping-address">
            <div class="box-content" id="shipping-address-display">
                <address><?php echo $this->renderAddress($this->getShippingAddress())?></address>
                <a href="#" id="edit-shipping-button"><?php echo $this->__('edit') ?></a>
            </div>
            <div class="box-content" id="shipping-address-form" style="display: none">
                <?php echo $this->getChildHtml('shipping') ?>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Shipping Method') ?></h3>
            </div>
            <div class="box-content">
                <form method="post" id="shipping_method_form" action="">
                    <?php if ($groups = $this->getShippingRateGroups()):?>
                        <?php $currentRate = $this->getCurrentShippingRate(); ?>
                        <fieldset>
                            <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
                                <?php if (!$currentRate):?>
                                    <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
                                <?php endif;?>
                                <?php foreach ($groups as $code => $rates):?>
                                    <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                                        <?php foreach ($rates as $rate):?>
                                            <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                                                <?php echo $this->renderShippingRateOption($rate)?>
                                            </option>
                                        <?php endforeach;?>
                                    </optgroup>
                                <?php endforeach;?>
                            </select>
                        </fieldset>
                        <p class="actions">
                            <button id="update_shipping_method_submit" type="submit" class="button"><span><span><?php echo $this->__('Update Shipping Method') ?></span></span></button>
                        </p>
                    <?php else: ?>
                        <p><strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong></p>
                    <?php endif;?>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="info-set col2-set">
    <h3 class="legend"><?php echo $this->__('Billing Information') ?></h3>
    <div class="col-1">
        <div class="box">
            <div class="box-content">
                <address><?php echo $this->renderAddress($this->getBillingAddress())?></address>
            </div>
        </div>
    </div>
</div>

<div class="info-set">
    <h3 class="legend"><?php echo $this->__('Items in Your Shopping Cart') ?></h3>
    <div id="details-reload">
        <?php echo $this->getChildHtml('details') ?>
    </div>
</div>

<?php echo $this->getChildHtml('agreements') ?>

<div class="buttons-set">
    <form id="place-order-form" action="<?php echo Mage::getUrl('mastercard/review/placeOrder') ?>" method="post">
        <button type="submit" id="place-order-button" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Place Order')) ?>"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
    </form>
</div>

<script type="text/javascript">
    var MpgsOrderReview = Class.create();
    MpgsOrderReview.prototype = {
        initialize: function () {
            $('place-order-form').on('submit', function (e) {
                e.preventDefault();
                var agreements = $('checkout-agreements');
                if (agreements) {
                    $A(agreements.querySelectorAll('input')).each(function (item) {
                        this.insert(item.clone().hide());
                    }.bind(this));
                }
                this.submit();
            });
            $('edit-shipping-button').on('click', function (e) {
                e.preventDefault();
                $('shipping-address-form').show();
                $('shipping-address-display').hide();
            });
            $('shipping-address-form-cancel').on('click', function (e) {
                e.preventDefault();
                $('shipping-address-form').hide();
                $('shipping-address-display').show();
            });
            $('shipping-address-form-save').on('click', function (e) {
                e.preventDefault();
                new Ajax.Request('<?php echo Mage::getUrl('mastercard/session/setShippingInformation') ?>', {
                    method: 'post',
                    parameters: $H($(shipping.form).serialize(true)),
                    onSuccess: this.didSaveShipping.bind(this),
                    onFailure: this.didFail.bind(this),
                    onLoading: function () {
                        console.log('loading');
                    }
                });
            }.bind(this));
            $('update_shipping_method_submit').on('click', function (e) {
                e.preventDefault();
                new Ajax.Request('<?php echo Mage::getUrl('mastercard/session/setShippingInformation') ?>', {
                    method: 'post',
                    parameters: $H({
                        shipping_method: $('shipping_method').value
                    }),
                    onSuccess: this.didSaveShipping.bind(this),
                    onFailure: this.didFail.bind(this),
                    onLoading: function () {
                        console.log('loading');
                    }
                });
            }.bind(this));
        },

        didSaveShipping: function () {
            window.location.reload();
        },

        didFail: function () {
            alert('<?php echo $this->__('Failed saving the shipping address/method, please try again.') ?>');
        }
    };
    new MpgsOrderReview();
</script>