<?php
/**
* Copyright (c) 2016-2019 Mastercard
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
?>

<table id="details-table" class="data-table linearize-table">
    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
    <?php endif; ?>
    <thead>
    <tr>
        <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product') ?></th>
        <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
        <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
        <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
    </tr>
    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <tr>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
        </tr>
    <?php endif; ?>
    </thead>
    <?php echo $this->getChildHtml('totals'); ?>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('details-table');</script>
