<?php
/**
 * Copyright (c) 2016-2019 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *
 * @see Mastercard_Mpgs_Block_System_Config_Fieldset_Hint
 */
?>
<div class="payment-notice">
	<br />
	<h4>Mastercard Payment Gateway Services</h4>
	<p>Mastercard has a single interface that allows organisations to
		process secure, multi-channel payments anywhere in the world.</p>
	<a target="blank" href="<?php echo $this->escapeHtml("http://www.mastercard.com/gateway") ?>"><?php echo Mage::helper('mpgs')->__('View Mastercard MPGS solutions.')?></a>
</div>
