<?php
/**
 * Copyright (c) 2016-2019 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<div>
    <span class="please-wait" id="mpgs-loading" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading...')) ?>" class="v-middle" /> <?php echo $this->__('Loading...') ?>
    </span>
    <span class="please-wait" id="mpgs-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
    </span>
</div>
<script type="text/javascript">
    var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
    var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';

    var HostedCheckout = Class.create();
    HostedCheckout.prototype = {
        config: {},
        button: null,
        originalSubmit: null,

        initialize: function (config) {
            this.config = config;
            this.button = $('onestepcheckout-place-order');
            this.form = $('onestepcheckout-form');
            this.originalSubmit = this.form.submit;
            this.form.submit = this.placeOrderSubmit.bind(this);

            get_save_billing_function(url_save_billing, url_set_methods, undefined, true)();
        },

        loadAdapter: function (callback) {
            if (typeof window.Checkout.configure !== 'undefined') {
                callback();
                return;
            }

            window.onMpgsError = this.onMpgsError.bind(this);
            window.onMpgsCancel = this.onMpgsCancel.bind(this);
            window.onMpgsComplete = this.onMpgsComplete.bind(this);

            var loader = new Element('script', {
                type: 'text/javascript',
                async: true,
                src: this.config.component_url,
                'data-error': 'onMpgsError',
                'data-cancel': 'onMpgsCancel',
                'data-complete': 'onMpgsComplete'
            });
            document.body.insert(loader);

            this.waitUntilReady(function () {
                callback();
            }.bind(this));
        },

        placeOrderSubmit: function () {
            if (window.payment.currentMethod !== 'Mastercard_hosted') {
                this.originalSubmit.apply(this.form);
                return;
            }

            this.button.disable();
            $('mpgs-loading').show();

            this.loadAdapter(function () {
                $('mpgs-loading').hide();
                this.openHostedSession();
            }.bind(this));
        },

        waitUntilReady: function (callback) {
            setTimeout(function() {
                if (typeof window.Checkout.configure !== 'undefined') {
                    callback();
                } else {
                    this.waitUntilReady(callback);
                }
            }.bind(this), 200);
        },

        noCache: function() {
            return '?_=' + Math.round(new Date().getTime() / 1000);
        },

        openHostedSession: function () {
            $('mpgs-loading').show();

            new Ajax.Request(this.config.create_session_url + this.noCache(), {
                requestHeaders: {
                    Accept: 'application/json'
                },
                parameters: {
                    cartId: this.config.cart_id
                },
                onSuccess: this.sessionCreated.bind(this),
                onFailure: this.sessionFailed.bind(this)
            });
        },

        sessionCreated: function (response) {
            Checkout.configure({
                merchant: this.config.merchant,
                session: {
                    id: response.responseJSON.SessionID,
                    version: response.responseJSON.SessionVersion
                },
                interaction: {
                    merchant: {
                        name: this.config.store_name
                    }
                }
            });
            Checkout.showLightbox();
        },

        sessionFailed: function (response) {
            $('mpgs-loading').hide();
            if (response.responseJSON) {
                alert(response.responseJSON.messages.error[0].message);
            } else {
                alert(""+response.statusText+", please contact the merchant.");
            }
            window.location.href = this.config.cancel_url;
        },

        onMpgsError: function (error) {
            $('mpgs-loading').hide();
            alert(error.cause + ' - ' + error.explanation);
            window.location.href = this.config.cancel_url;
        },

        onMpgsCancel: function () {
            window.location.href = this.config.cancel_url;
        },

        onMpgsComplete: function (resultIndicator, sessionVersion) {
            $('mpgs-loading').hide();
            $('mpgs-please-wait').show();

            var input = new Element('input', {
                type: 'hidden',
                id: 'res_code',
                name: 'res_code',
                value: resultIndicator
            });

            this.form.appendChild(input);
            this.originalSubmit.apply(this.form);
        }
    };
    new HostedCheckout(<?php echo $this->getJsConfig() ?>);
</script>
